### ISSUE TITLE
Upgrade PureScript version?

### ISSUE THREAD

**Issue by jgarte** [newlandsvalley/purescript-abc-scores#82]
Hi, what do you suggest for fixing this error?

```
λ spago install && npm run build
[error] Oh noes! It looks like the PureScript version installed on your system is not compatible with the package-set you're using.

installed `purs` version:    0.15.4
minimum package-set version: 0.13.8

There are a few ways to solve this:
- install a compatible `purs` version (i.e. in the same 'semver range' as the one in the package set)
- if the `purs` version is 'too new', you can try using `spago upgrade-set` to upgrade to the latest package set
- if you know what you're doing and you want to disable this check, you can override the `version` of the `metadata` package in the packages.dhall, e.g.:

  let upstream = <package-set url here>
  in  upstream
    with metadata.version = "v0.15.4"
```

**Comment by newlandsvalley** [comment]
Please be a bit patient.  The PureScript 15 compatible branch is ```ps015```.  The new ```Registry``` has an issue where it doesn't yet update package sets - see https://github.com/purescript/registry/actions. This should be fixed (I hope) within a couple of days.  When it is, I'll have the ```abc-parser``` dependency in package sets the absence of which has been a blight on development for me for the last 2 years or so.  And then I'll be able to merge the ```ps015``` branch into ```Master```.  (And I can also start to do this for all my other projects that have been stymied in this way).

**Comment by newlandsvalley** [comment]
master is now compatible with PureScript 0.15.4.
